function [RMaLosChan,RMaLosChanH,txWaveform,Param] = RMaLos(d2D,fc)

[Param] = initializeParam(d2D,fc);

%create Tx waveform
if fc == 6e9 
enb.NDLRB = 100;   %20MHz
else
enb.NDLRB = 110;   %Max system bW
end

enb.CyclicPrefix = 'Normal';
grid = lteDLResourceGrid(enb,64);
grid(:) = lteSymbolModulate(randi([0 1],numel(grid)*2,1),'QPSK');
[txWaveform,txInfo] = lteOFDMModulate(enb,grid);

%antenna array 
txAntennaArray = struct('Size',[4,4,2,1,2],'ElementSpacing',[0.5,0.5,2.5,2.5],'PolarizationAngles',[45,-45],'Orientation',[0;102;0],'Element','38.900');
rxAntennaArray = struct('Size',[1,1,2,1,1],'ElementSpacing',[0.5,0.5,2.5,2.5],'PolarizationAngles',[0,90],'Orientation',[0;0;0],'Element','isotropic');

%Create UMiSC channel LOS 
RMaLosChan = nr5gCDLChannelLos(...
    'DelayProfile', 'CDL-D',...            
    'AngleScaling', true,...             
    'AngleSpreads', [Param.cASD, Param.cASA, Param.cZSD, Param.cZSA],...           
    'MeanAngles', [Param.uASD, Param.uASA, Param.uZSD, Param.uZSA],...             
    'DelaySpread', Param.DsDesired, ...           
    'CarrierFrequency', Param.fc,...
    'MaximumDopplerShift', Param.maxDopShift,...   
    'KFactorScaling', true,...
    'KFactor', Param.Kfactor,...
    'SampleRate', txInfo.SamplingRate,...              
    'TransmitAntennaArray', txAntennaArray,...    
    'ReceiveAntennaArray' , rxAntennaArray,...    
    'SampleDensity', 64);  

RMaLosChanH = nr5gCDLChannelLosH(...
    'DelayProfile', 'CDL-D',...            
    'AngleScaling', true,...             
    'AngleSpreads', [Param.cASD, Param.cASA, Param.cZSD, Param.cZSA],...           
    'MeanAngles', [Param.uASD, Param.uASA, Param.uZSD, Param.uZSA],...             
    'DelaySpread', Param.DsDesired, ...           
    'CarrierFrequency', Param.fc,...
    'MaximumDopplerShift', Param.maxDopShift,...   
    'KFactorScaling', true,...
    'KFactor', Param.Kfactor,...
    'SampleRate', txInfo.SamplingRate,...              
    'TransmitAntennaArray', txAntennaArray,...    
    'ReceiveAntennaArray' , rxAntennaArray,...    
    'SampleDensity', 64);  



% analyzer = dsp.SpectrumAnalyzer('SampleRate',UMiScLosChan.SampleRate);
% analyzer.Title = ['Received signal spectrum for' UMiScLosChan.DelayProfile];
% analyzer(rxWaveform);
end 
